g++ -o tp5 tp5.cpp `pkg-config --cflags --libs gumbo`
echo "Query 1"
./tp5 "claudio moises"
echo "Query 2"
./tp5 "ufmg computacao"
echo "Query 3"
./tp5 "google computacao"
echo "Query 4"
./tp5 "uol bh minas gerais"
echo "Query 5"
./tp5 "firefox galinha pintadinha"
echo "Query 6"
./tp5 "download torrent filmes"
echo "Query 7"
./tp5 "aluguel de casa bh"
echo "Query 8"
./tp5 "compra imovel salvador"
echo "Query 9"
./tp5 "teclado comprar ilheus"
echo "Query 10"
./tp5 "escola ilheus centro"
echo "Query 11"
./tp5 "auto escola centro salvador"
echo "Query 12"
./tp5 "livro modern information retrieval"
echo "Query 13"
./tp5 "google brasil sao paulo"
echo "Query 14"
./tp5 "feira valenca"
echo "Query 15"
./tp5 "recuperacao de informacao"
echo "Query 16"
./tp5 "melhor navegador da web"
echo "Query 17"
./tp5 "casa alugar ouro preto"
echo "Query 18"
./tp5 "hospital belo horizonte"
echo "Query 19"
./tp5 "comprar tinta belo horizonte"
echo "Query 20"
./tp5 "alugar carro para passeio ilheus"
echo "Query 21"
./tp5 "assistir filme sao paulo"
echo "Query 22"
./tp5 "alugar filme belo horizonte"
echo "Query 23"
./tp5 "posto de gasolina belo horizonte"
echo "Query 24"
./tp5 "padaria pao doce salvador"
echo "Query 25"
./tp5 "maquina de busca na internet"
