g++ -o tp5 tp5.cpp `pkg-config --cflags --libs gumbo`
echo "Query 1"
./tp5 "fundacao oswaldo cruz"
echo "Query 2"
./tp5 "espn"
echo "Query 3"
./tp5 "cyberpunk 2077"
echo "Query 4"
./tp5 "joe biden"
echo "Query 5"
./tp5 "enem 2020"
echo "Query 6"
./tp5 "sapiens breve história humanidade"
echo "Query 7"
./tp5 "o que e pix"
echo "Query 8"
./tp5 "pringles 118g"
echo "Query 9"
./tp5 "formula de bhaskara"
echo "Query 10"
./tp5 "auxilio emergencial"
echo "Query 11"
./tp5 "poderoso chefao"
echo "Query 12"
./tp5 "samsung galaxy a21"
echo "Query 13"
./tp5 "receita sorvete de gelatina"
echo "Query 14"
./tp5 "agricultura de soja brasileira"
echo "Query 15"
./tp5 "como fazer a declaracao de imposto de renda"
echo "Query 16"
./tp5 "santos dummont"
echo "Query 17"
./tp5 "desmatamento amazonia"
echo "Query 18"
./tp5 "vencedores do campeonato brasileiro"
echo "Query 19"
./tp5 "como escrever escassez"
echo "Query 20"
./tp5 "como fazer academia em casa"
